version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mood_movie_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mada
      - POSTGRES_DB=mood_movie_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
