name: CI/CD Pipeline for Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Note: This step will fail until package.json is created
      - name: Install dependencies
        run: npm install

      # Note: This step will fail until tests are configured
      - name: Run tests
        run: npm test

      # Note: This step will fail until build script is configured
      - name: Build project
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Note: This step will fail until package.json is created
      - name: Install dependencies
        run: npm install

      # Note: This step will fail until tests are configured
      - name: Run tests
        run: npm test
